// Code generated by "stringer -type=ControlByte"; DO NOT EDIT.

package gbcf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACK-170]
	_ = x[NAK-240]
	_ = x[END-15]
	_ = x[DATA-85]
}

const (
	_ControlByte_name_0 = "END"
	_ControlByte_name_1 = "DATA"
	_ControlByte_name_2 = "ACK"
	_ControlByte_name_3 = "NAK"
)

func (i ControlByte) String() string {
	switch {
	case i == 15:
		return _ControlByte_name_0
	case i == 85:
		return _ControlByte_name_1
	case i == 170:
		return _ControlByte_name_2
	case i == 240:
		return _ControlByte_name_3
	default:
		return "ControlByte(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
